### ISSUE TITLE
UserRole matching query does not exist exception is thrown when database is migrated

### ISSUE THREAD

**Issue by AstiaSun** [RetroFlow/retro-flow-api#1]
**Pre-steps:**
Remove all created board migrations

**Steps to reproduce:**

1. $ python manage.py makemigrations board
2. $ python manage.py migrate

_Expected:_ migrations done successfully
_Actual:_ board.models.teams.UserRole.get_default_role throws an exception: board.models.team.DoesNotExist: UserRole matching query does not exist.

**Comment by mashakereb** [comment]
This is not a problem. To run migrations use: bash scripts/migrate.sh
